repos:
  - repo: local
    hooks:
    - id: cargo check
      name: cargo check
      description: Check the package for errors
      entry: cargo check
      args: ["--workspace"]
      language: system
      types: [rust]
      pass_filenames: false
      stages: [pre-commit]
    - id: clippy
      name: cargo clippy
      description: Lint rust sources
      entry: cargo clippy
      language: system
      args: ["--all", "--", "-D", "warnings"]
      types: [rust]
      pass_filenames: false
      stages: [pre-commit]
    - id: fmt
      name: cargo fmt
      description: Format files with cargo fmt
      entry: cargo fmt
      language: system
      types: [rust]
      args: ["--all", "--"]
      stages: [pre-commit]
  - repo: https://github.com/biomejs/pre-commit
    rev: v2.3.8 # Use the sha / tag you want to point at
    hooks:
      - id: biome-check
        files: ".(css|js|ts)"
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    - id: check-byte-order-marker
      stages: [pre-commit]
    - id: check-case-conflict
      stages: [pre-commit]
    - id: check-merge-conflict
      stages: [pre-commit]
    - id: check-symlinks
      stages: [pre-commit]
    - id: check-yaml
      stages: [pre-commit]
    - id: check-json
      stages: [pre-commit]
    - id: end-of-file-fixer
      stages: [pre-commit]
    - id: mixed-line-ending
      stages: [pre-commit]
    - id: trailing-whitespace
      stages: [pre-commit]
  - repo: https://github.com/espressif/conventional-precommit-linter
    rev: v1.10.0
    hooks:
      - id: conventional-precommit-linter
        stages: [commit-msg]
        args:
          # https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum
          - --types=[build,chore,ci,docs,feat,fix,perf,refactor,revert,style,test]
