max_width = 100

# imports_granularity = "Crate"
# group_imports = "StdExternalCrate"

comment_width = 100
# wrap_comments = true
# format_code_in_doc_comments = true

match_block_trailing_comma = true

# normalize_comments = true
# normalize_doc_attributes = true
